### ISSUE TITLE
[Refactoring] guard 문 합치기

### ISSUE THREAD

**Issue by fimuxd** [JennPaskua4160/repos_rainist#4]
여러개의 가드문이 동일한 return 값을 가질 경우 하나로 묶을 수 있습니다.

예)
```swift
guard 
     let name = names.first, 
     !age = ages.isEmpty
else { return }
```

**Comment by fimuxd** [comment]
해당 이슈 외 2개(#2  #3 )의 이슈, 총 3개를 올렸는데요. 
각 이슈에 대해 리팩토링을 하여 PR 작성 부탁드립니다. 

> 협업과 병행하여 과제 작성하시느라 고생 많으셨습니다. 소중한 주말을 레이니스트에 할애해주셔서 감사합니다. 🙏

**Comment by JennPaskua4160** [comment]
이슈 수정하였습니다. :)
